spring.application.name=hotel-back

server.port=${SERVER_PORT}
#server.ssl.enabled=true
#server.ssl.key-store=path
#server.ssl.key-store-password=pass
#server.ssl.key-store-type=PKCS12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
db.url=${DB_URL}
db.user=${DB_USER}
db.password=${DB_PASSWORD}

# secret + spring security first password = jwt.secret -> base64
jwt.secret=${JWT_SECRET}